// flow-typed signature: b5229613ee0d8ce09d2351292ffece9b
// flow-typed version: <<STUB>>/babel-preset-flow-runtime_v^0.7.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-flow-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-flow-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-flow-runtime/index' {
  declare module.exports: $Exports<'babel-preset-flow-runtime'>;
}
declare module 'babel-preset-flow-runtime/index.js' {
  declare module.exports: $Exports<'babel-preset-flow-runtime'>;
}
