// flow-typed signature: 52ca76cfab8a33b8451e80242efeb242
// flow-typed version: <<STUB>>/@chantelle/config_v^0.0.1-y.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chantelle/config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chantelle/config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chantelle/config/backpack.config' {
  declare module.exports: any;
}

declare module '@chantelle/config/build/main' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/@babel/register_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/@chantelle/scripts_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/@chantelle/util_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/autoprefixer_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/babel-register_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/backpack-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/case-sensitive-paths-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/css-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/dotenv_v4.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/eslint-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/extract-text-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/file-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/flow-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/html-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/jquery_v3.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/less_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/less-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/nodemon_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/object-assign_v4.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/postcss-flexbugs-fixes_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/postcss-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/react-dev-utils_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/react-scripts_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/style-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/sw-precache-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/url-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/webpack-manifest-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/flow-typed/npm/whatwg-fetch_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/config/getJestCssTransform' {
  declare module.exports: any;
}

declare module '@chantelle/config/getJestFileTransform' {
  declare module.exports: any;
}

declare module '@chantelle/config/getWebpackDevelopment' {
  declare module.exports: any;
}

declare module '@chantelle/config/getWebpackDevServer' {
  declare module.exports: any;
}

declare module '@chantelle/config/getWebpackProduction' {
  declare module.exports: any;
}

declare module '@chantelle/config/index.test' {
  declare module.exports: any;
}

declare module '@chantelle/config/src/env' {
  declare module.exports: any;
}

declare module '@chantelle/config/src/index' {
  declare module.exports: any;
}

declare module '@chantelle/config/src/jestCssTransform' {
  declare module.exports: any;
}

declare module '@chantelle/config/src/jestFileTransform' {
  declare module.exports: any;
}

declare module '@chantelle/config/src/paths' {
  declare module.exports: any;
}

declare module '@chantelle/config/src/polyfills' {
  declare module.exports: any;
}

declare module '@chantelle/config/src/webpackDevelopment' {
  declare module.exports: any;
}

declare module '@chantelle/config/src/webpackDevServer' {
  declare module.exports: any;
}

declare module '@chantelle/config/src/webpackProduction' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chantelle/config/backpack.config.js' {
  declare module.exports: $Exports<'@chantelle/config/backpack.config'>;
}
declare module '@chantelle/config/build/main.js' {
  declare module.exports: $Exports<'@chantelle/config/build/main'>;
}
declare module '@chantelle/config/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/@babel/register_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/@babel/register_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/@chantelle/scripts_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/@chantelle/scripts_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/@chantelle/util_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/@chantelle/util_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/autoprefixer_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/autoprefixer_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/babel-register_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/babel-register_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/backpack-core_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/backpack-core_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/case-sensitive-paths-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/case-sensitive-paths-webpack-plugin_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/css-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/css-loader_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/dotenv_v4.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/dotenv_v4.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/eslint-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/eslint-loader_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/extract-text-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/extract-text-webpack-plugin_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/file-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/file-loader_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/flow-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/flow-runtime_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/html-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/html-webpack-plugin_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/jquery_v3.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/jquery_v3.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/less_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/less_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/less-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/less-loader_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/nodemon_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/nodemon_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/object-assign_v4.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/object-assign_v4.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/postcss-flexbugs-fixes_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/postcss-flexbugs-fixes_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/postcss-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/postcss-loader_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/react-dev-utils_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/react-dev-utils_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/react-scripts_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/react-scripts_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/style-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/style-loader_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/sw-precache-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/sw-precache-webpack-plugin_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/url-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/url-loader_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/webpack_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/webpack-manifest-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/webpack-manifest-plugin_vx.x.x'>;
}
declare module '@chantelle/config/flow-typed/npm/whatwg-fetch_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/config/flow-typed/npm/whatwg-fetch_vx.x.x'>;
}
declare module '@chantelle/config/getJestCssTransform.js' {
  declare module.exports: $Exports<'@chantelle/config/getJestCssTransform'>;
}
declare module '@chantelle/config/getJestFileTransform.js' {
  declare module.exports: $Exports<'@chantelle/config/getJestFileTransform'>;
}
declare module '@chantelle/config/getWebpackDevelopment.js' {
  declare module.exports: $Exports<'@chantelle/config/getWebpackDevelopment'>;
}
declare module '@chantelle/config/getWebpackDevServer.js' {
  declare module.exports: $Exports<'@chantelle/config/getWebpackDevServer'>;
}
declare module '@chantelle/config/getWebpackProduction.js' {
  declare module.exports: $Exports<'@chantelle/config/getWebpackProduction'>;
}
declare module '@chantelle/config/index.test.js' {
  declare module.exports: $Exports<'@chantelle/config/index.test'>;
}
declare module '@chantelle/config/src/env.js' {
  declare module.exports: $Exports<'@chantelle/config/src/env'>;
}
declare module '@chantelle/config/src/index.js' {
  declare module.exports: $Exports<'@chantelle/config/src/index'>;
}
declare module '@chantelle/config/src/jestCssTransform.js' {
  declare module.exports: $Exports<'@chantelle/config/src/jestCssTransform'>;
}
declare module '@chantelle/config/src/jestFileTransform.js' {
  declare module.exports: $Exports<'@chantelle/config/src/jestFileTransform'>;
}
declare module '@chantelle/config/src/paths.js' {
  declare module.exports: $Exports<'@chantelle/config/src/paths'>;
}
declare module '@chantelle/config/src/polyfills.js' {
  declare module.exports: $Exports<'@chantelle/config/src/polyfills'>;
}
declare module '@chantelle/config/src/webpackDevelopment.js' {
  declare module.exports: $Exports<'@chantelle/config/src/webpackDevelopment'>;
}
declare module '@chantelle/config/src/webpackDevServer.js' {
  declare module.exports: $Exports<'@chantelle/config/src/webpackDevServer'>;
}
declare module '@chantelle/config/src/webpackProduction.js' {
  declare module.exports: $Exports<'@chantelle/config/src/webpackProduction'>;
}
