// flow-typed signature: a82691f8d3c047d3fdfa7968cfc2ba5e
// flow-typed version: <<STUB>>/@chantelle/gulp-tasks_v^0.0.1-y.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chantelle/gulp-tasks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chantelle/gulp-tasks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chantelle/gulp-tasks/build/main' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/@babel/register_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/@chantelle/config_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/@chantelle/scripts_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/@chantelle/util_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/babel-register_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/backpack-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/backpack-core-babel-7_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/flow-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-exec_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-lebab_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-load-plugins_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-print_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-shell_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-util_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/nodemon_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/react-scripts_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/index.test' {
  declare module.exports: any;
}

declare module '@chantelle/gulp-tasks/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chantelle/gulp-tasks/build/main.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/build/main'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/@babel/register_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/@babel/register_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/@chantelle/config_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/@chantelle/config_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/@chantelle/scripts_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/@chantelle/scripts_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/@chantelle/util_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/@chantelle/util_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/babel-register_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/babel-register_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/backpack-core_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/backpack-core_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/backpack-core-babel-7_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/backpack-core-babel-7_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/flow-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/flow-runtime_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/gulp_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-env_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/gulp-env_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/gulp-eslint_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-exec_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/gulp-exec_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-lebab_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/gulp-lebab_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-load-plugins_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/gulp-load-plugins_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-print_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/gulp-print_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-shell_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/gulp-shell_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/gulp-util_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/gulp-util_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/nodemon_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/nodemon_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/react-scripts_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/react-scripts_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/flow-typed/npm/webpack_vx.x.x'>;
}
declare module '@chantelle/gulp-tasks/index' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks'>;
}
declare module '@chantelle/gulp-tasks/index.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks'>;
}
declare module '@chantelle/gulp-tasks/index.test.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/index.test'>;
}
declare module '@chantelle/gulp-tasks/src/index.js' {
  declare module.exports: $Exports<'@chantelle/gulp-tasks/src/index'>;
}
