// flow-typed signature: 6561bca98646958825a57353182ff7b1
// flow-typed version: <<STUB>>/@chantelle/eslint-config-chantelle-commonjs_v0.0.1-y.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chantelle/eslint-config-chantelle-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chantelle/eslint-config-chantelle-commonjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/@chantelle/eslint-config-chantelle-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/@chantelle/eslint-plugin-chantelle_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/react-scripts_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/@chantelle/eslint-config-chantelle-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/@chantelle/eslint-config-chantelle-commonjs_vx.x.x'>;
}
declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/@chantelle/eslint-plugin-chantelle_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/@chantelle/eslint-plugin-chantelle_vx.x.x'>;
}
declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/prettier_vx.x.x'>;
}
declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/react-scripts_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/react-scripts_vx.x.x'>;
}
declare module '@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle-commonjs/flow-typed/npm/webpack_vx.x.x'>;
}
declare module '@chantelle/eslint-config-chantelle-commonjs/index' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle-commonjs'>;
}
declare module '@chantelle/eslint-config-chantelle-commonjs/index.js' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle-commonjs'>;
}
