// flow-typed signature: 871b3b0845eecd87bcf3f5a1855dc2bf
// flow-typed version: <<STUB>>/@chantelle/scripts_v^0.0.1-y.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chantelle/scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chantelle/scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chantelle/scripts/backpack.config' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/bin/link-legacy' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/bin/postinstall-legacy' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/bin/precommit' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/bin/run-gulp' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/bin/start-legacy' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/bin/start' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/bin/test' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/build/main' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/@babel/register_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/@chantelle/config_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/@chantelle/gulp-tasks_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/@chantelle/util_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/backpack-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/backpack-core-babel-7_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/dotenv_v4.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/flow-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/fs-extra_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/glob_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/gulp_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/jest_v21.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/nodemon_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/react-dev-utils_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/react-scripts_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/shelljs_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/flow-typed/npm/webpack-dev-server_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/gulpfile.babel' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/index.test' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/src/build' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/src/index' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/src/run-gulp-task' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/src/start' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/src/test' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/translations/config' {
  declare module.exports: any;
}

declare module '@chantelle/scripts/translations/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chantelle/scripts/backpack.config.js' {
  declare module.exports: $Exports<'@chantelle/scripts/backpack.config'>;
}
declare module '@chantelle/scripts/bin/link-legacy.js' {
  declare module.exports: $Exports<'@chantelle/scripts/bin/link-legacy'>;
}
declare module '@chantelle/scripts/bin/postinstall-legacy.js' {
  declare module.exports: $Exports<'@chantelle/scripts/bin/postinstall-legacy'>;
}
declare module '@chantelle/scripts/bin/precommit.js' {
  declare module.exports: $Exports<'@chantelle/scripts/bin/precommit'>;
}
declare module '@chantelle/scripts/bin/run-gulp.js' {
  declare module.exports: $Exports<'@chantelle/scripts/bin/run-gulp'>;
}
declare module '@chantelle/scripts/bin/start-legacy.js' {
  declare module.exports: $Exports<'@chantelle/scripts/bin/start-legacy'>;
}
declare module '@chantelle/scripts/bin/start.js' {
  declare module.exports: $Exports<'@chantelle/scripts/bin/start'>;
}
declare module '@chantelle/scripts/bin/test.js' {
  declare module.exports: $Exports<'@chantelle/scripts/bin/test'>;
}
declare module '@chantelle/scripts/build/main.js' {
  declare module.exports: $Exports<'@chantelle/scripts/build/main'>;
}
declare module '@chantelle/scripts/flow-typed/npm/@babel/register_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/@babel/register_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/@chantelle/config_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/@chantelle/config_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/@chantelle/gulp-tasks_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/@chantelle/gulp-tasks_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/@chantelle/util_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/@chantelle/util_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/backpack-core_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/backpack-core_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/backpack-core-babel-7_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/backpack-core-babel-7_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/dotenv_v4.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/dotenv_v4.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/flow-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/flow-runtime_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/fs-extra_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/fs-extra_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/glob_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/glob_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/gulp_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/gulp_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/jest_v21.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/jest_v21.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/nodemon_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/nodemon_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/react-dev-utils_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/react-dev-utils_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/react-scripts_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/react-scripts_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/shelljs_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/shelljs_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/webpack_vx.x.x'>;
}
declare module '@chantelle/scripts/flow-typed/npm/webpack-dev-server_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/scripts/flow-typed/npm/webpack-dev-server_vx.x.x'>;
}
declare module '@chantelle/scripts/gulpfile.babel.js' {
  declare module.exports: $Exports<'@chantelle/scripts/gulpfile.babel'>;
}
declare module '@chantelle/scripts/index.test.js' {
  declare module.exports: $Exports<'@chantelle/scripts/index.test'>;
}
declare module '@chantelle/scripts/src/build.js' {
  declare module.exports: $Exports<'@chantelle/scripts/src/build'>;
}
declare module '@chantelle/scripts/src/index.js' {
  declare module.exports: $Exports<'@chantelle/scripts/src/index'>;
}
declare module '@chantelle/scripts/src/run-gulp-task.js' {
  declare module.exports: $Exports<'@chantelle/scripts/src/run-gulp-task'>;
}
declare module '@chantelle/scripts/src/start.js' {
  declare module.exports: $Exports<'@chantelle/scripts/src/start'>;
}
declare module '@chantelle/scripts/src/test.js' {
  declare module.exports: $Exports<'@chantelle/scripts/src/test'>;
}
declare module '@chantelle/scripts/translations/config.js' {
  declare module.exports: $Exports<'@chantelle/scripts/translations/config'>;
}
declare module '@chantelle/scripts/translations/index.js' {
  declare module.exports: $Exports<'@chantelle/scripts/translations/index'>;
}
