// flow-typed signature: d59c9dc6414fe029abb25b78e43e8271
// flow-typed version: <<STUB>>/@nod/debug-with-package-name_v^1.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nod/debug-with-package-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nod/debug-with-package-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nod/debug-with-package-name/backpack.config' {
  declare module.exports: any;
}

declare module '@nod/debug-with-package-name/build/index' {
  declare module.exports: any;
}

declare module '@nod/debug-with-package-name/build/lib' {
  declare module.exports: any;
}

declare module '@nod/debug-with-package-name/src/index' {
  declare module.exports: any;
}

declare module '@nod/debug-with-package-name/src/lib' {
  declare module.exports: any;
}

declare module '@nod/debug-with-package-name/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nod/debug-with-package-name/backpack.config.js' {
  declare module.exports: $Exports<'@nod/debug-with-package-name/backpack.config'>;
}
declare module '@nod/debug-with-package-name/build/index.js' {
  declare module.exports: $Exports<'@nod/debug-with-package-name/build/index'>;
}
declare module '@nod/debug-with-package-name/build/lib.js' {
  declare module.exports: $Exports<'@nod/debug-with-package-name/build/lib'>;
}
declare module '@nod/debug-with-package-name/src/index.js' {
  declare module.exports: $Exports<'@nod/debug-with-package-name/src/index'>;
}
declare module '@nod/debug-with-package-name/src/lib.js' {
  declare module.exports: $Exports<'@nod/debug-with-package-name/src/lib'>;
}
declare module '@nod/debug-with-package-name/test/index.test.js' {
  declare module.exports: $Exports<'@nod/debug-with-package-name/test/index.test'>;
}
