// flow-typed signature: 40ba160d2f1bfa0637ae29933887f09f
// flow-typed version: <<STUB>>/@nod/debug-with-package-name_v^0.1.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nod/debug-with-package-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nod/debug-with-package-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nod/debug-with-package-name/lib' {
  declare module.exports: any;
}

declare module '@nod/debug-with-package-name/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nod/debug-with-package-name/index' {
  declare module.exports: $Exports<'@nod/debug-with-package-name'>;
}
declare module '@nod/debug-with-package-name/index.js' {
  declare module.exports: $Exports<'@nod/debug-with-package-name'>;
}
declare module '@nod/debug-with-package-name/lib.js' {
  declare module.exports: $Exports<'@nod/debug-with-package-name/lib'>;
}
declare module '@nod/debug-with-package-name/test/index.test.js' {
  declare module.exports: $Exports<'@nod/debug-with-package-name/test/index.test'>;
}
