module.exports = { //eslint-disable-line
  'flowtype/define-flow-type': 1,
  'flowtype/require-parameter-type': [ 2, { 'excludeArrowFunctions': true } ],
  'flowtype/require-return-type': 0,
  'flowtype/space-after-type-colon': 0,
  'flowtype/space-before-type-colon': 0,
  'flowtype/type-id-match': 0,
  'flowtype/use-flow-type': 1,
  'flowtype/valid-syntax': 2,

  'babel/object-curly-spacing': [1, 'always'],

  'import/no-duplicates': 2,
  'import/no-deprecated': 1,

  'react/no-did-mount-set-state': 2,
  'react/no-did-update-set-state': 2,
  'react/no-direct-mutation-state': 2,
  'react/no-is-mounted': 2,
  'react/no-unknown-property': 1,
  'react/prop-types': 1,
  'react/prefer-stateless-function': 1,
  'react/react-in-jsx-scope': 1,
  'react/self-closing-comp': 1,

  'indent': [ 2, 2, { 'SwitchCase': 1 } ],
  'jsx-quotes': 2,
  'comma-style': [ 2, 'last', {
    'exceptions': { 'ArrayExpression': true, 'ObjectExpression': true },
  }],
  'arrow-parens': [ 2, 'as-needed' ],
  'comma-dangle': [ 2, 'always-multiline' ],
  'key-spacing': [ 2, {
    'beforeColon': false,
    'afterColon': true,
  }],

  'no-delete-var': 1,
  'no-self-assign': 2,
  'no-return-await': 2,
  'no-loop-func': 2,
  'no-unreachable': 2,
  'strict': 1,
  'prefer-const': 0,
  'no-await-in-loop': 1,
  'no-dupe-class-members': 2,
  'generator-star-spacing': [ 2, 'both' ],
  'no-irregular-whitespace': 2,
  'semi': [ 1, 'never' ],
  'quotes': [ 2, 'single' ],
  'max-statements-per-line': [ 2, { 'max': 2 } ],
  'array-bracket-spacing': [ 0, 'always' ],
  'space-before-blocks': [ 2, 'always' ],
  'template-curly-spacing': [ 2, 'always' ],
  'max-len': [1, 80],
}
