// flow-typed signature: 38e93cf84d3b0f0389cd3d5bad00b5ba
// flow-typed version: <<STUB>>/eslint-config-cleanjs_v^4.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-cleanjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-cleanjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-cleanjs/index' {
  declare module.exports: $Exports<'eslint-config-cleanjs'>;
}
declare module 'eslint-config-cleanjs/index.js' {
  declare module.exports: $Exports<'eslint-config-cleanjs'>;
}
