// flow-typed signature: da377d568553424ce4641744228c8595
// flow-typed version: <<STUB>>/gulp-print_v^2.0.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-print'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-print' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-print/lib/gulp-print' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-print/lib/gulp-print.js' {
  declare module.exports: $Exports<'gulp-print/lib/gulp-print'>;
}
