// flow-typed signature: 5460671cecb63b9944da0e8240218339
// flow-typed version: <<STUB>>/gulp-lebab_v*/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-lebab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-lebab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-lebab/index' {
  declare module.exports: $Exports<'gulp-lebab'>;
}
declare module 'gulp-lebab/index.js' {
  declare module.exports: $Exports<'gulp-lebab'>;
}
