// flow-typed signature: f1366a16ba948a990b327464381166bf
// flow-typed version: <<STUB>>/@chantelle/util_v^0.0.1-y.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chantelle/util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chantelle/util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chantelle/util/backpack.config' {
  declare module.exports: any;
}

declare module '@chantelle/util/build/main' {
  declare module.exports: any;
}

declare module '@chantelle/util/build/public/static/js/bundle.9e8cf919' {
  declare module.exports: any;
}

declare module '@chantelle/util/flow-typed/npm/@nod/debug-with-package-name_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/util/flow-typed/npm/backpack-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/util/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/util/flow-typed/npm/flow-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/util/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/util/flow-typed/npm/nodemon_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/util/flow-typed/npm/react-scripts_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/util/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/util/index.test' {
  declare module.exports: any;
}

declare module '@chantelle/util/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chantelle/util/backpack.config.js' {
  declare module.exports: $Exports<'@chantelle/util/backpack.config'>;
}
declare module '@chantelle/util/build/main.js' {
  declare module.exports: $Exports<'@chantelle/util/build/main'>;
}
declare module '@chantelle/util/build/public/static/js/bundle.9e8cf919.js' {
  declare module.exports: $Exports<'@chantelle/util/build/public/static/js/bundle.9e8cf919'>;
}
declare module '@chantelle/util/flow-typed/npm/@nod/debug-with-package-name_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/util/flow-typed/npm/@nod/debug-with-package-name_vx.x.x'>;
}
declare module '@chantelle/util/flow-typed/npm/backpack-core_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/util/flow-typed/npm/backpack-core_vx.x.x'>;
}
declare module '@chantelle/util/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@chantelle/util/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@chantelle/util/flow-typed/npm/flow-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/util/flow-typed/npm/flow-runtime_vx.x.x'>;
}
declare module '@chantelle/util/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/util/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@chantelle/util/flow-typed/npm/nodemon_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/util/flow-typed/npm/nodemon_vx.x.x'>;
}
declare module '@chantelle/util/flow-typed/npm/react-scripts_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/util/flow-typed/npm/react-scripts_vx.x.x'>;
}
declare module '@chantelle/util/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/util/flow-typed/npm/webpack_vx.x.x'>;
}
declare module '@chantelle/util/index.test.js' {
  declare module.exports: $Exports<'@chantelle/util/index.test'>;
}
declare module '@chantelle/util/src/index.js' {
  declare module.exports: $Exports<'@chantelle/util/src/index'>;
}
