// flow-typed signature: 3e6c208a9a3acd7883fb4f2a6d16c3b0
// flow-typed version: <<STUB>>/backpack-core-babel-7_v^0.6.1/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'backpack-core-babel-7'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'backpack-core-babel-7' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'backpack-core-babel-7/babel' {
  declare module.exports: any;
}

declare module 'backpack-core-babel-7/config/paths' {
  declare module.exports: any;
}

declare module 'backpack-core-babel-7/config/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'backpack-core-babel-7/babel.js' {
  declare module.exports: $Exports<'backpack-core-babel-7/babel'>;
}
declare module 'backpack-core-babel-7/config/paths.js' {
  declare module.exports: $Exports<'backpack-core-babel-7/config/paths'>;
}
declare module 'backpack-core-babel-7/config/webpack.config.js' {
  declare module.exports: $Exports<'backpack-core-babel-7/config/webpack.config'>;
}
