// flow-typed signature: 4882a40942f7472ba33f379bd51d23fc
// flow-typed version: <<STUB>>/yarn-or-npm_v^2.0.4/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarn-or-npm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarn-or-npm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yarn-or-npm/bin/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yarn-or-npm/bin/index.js' {
  declare module.exports: $Exports<'yarn-or-npm/bin/index'>;
}
declare module 'yarn-or-npm/index' {
  declare module.exports: $Exports<'yarn-or-npm'>;
}
declare module 'yarn-or-npm/index.js' {
  declare module.exports: $Exports<'yarn-or-npm'>;
}
