// flow-typed signature: c4926b8a7ed94501d976378d6078c00b
// flow-typed version: <<STUB>>/@babel/plugin-syntax-pipeline-operator_v^7.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-pipeline-operator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-pipeline-operator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-pipeline-operator/lib/index' {
  declare module.exports: any;
}

declare module '@babel/plugin-syntax-pipeline-operator/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-pipeline-operator/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-pipeline-operator/lib/index'>;
}
declare module '@babel/plugin-syntax-pipeline-operator/src/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-pipeline-operator/src/index'>;
}
