// flow-typed signature: 471f2b0138e2653bddd7a3755590a8c6
// flow-typed version: <<STUB>>/@chantelle/babel-preset-chantelle_v^0.0.1-y.5/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chantelle/babel-preset-chantelle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chantelle/babel-preset-chantelle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@chantelle/babel-preset-chantelle/index' {
  declare module.exports: $Exports<'@chantelle/babel-preset-chantelle'>;
}
declare module '@chantelle/babel-preset-chantelle/index.js' {
  declare module.exports: $Exports<'@chantelle/babel-preset-chantelle'>;
}
