// flow-typed signature: ef9f9255992f05bac9414c220d5d4613
// flow-typed version: <<STUB>>/@chantelle/eslint-plugin-chantelle_v^0.0.1-y.4/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chantelle/eslint-plugin-chantelle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chantelle/eslint-plugin-chantelle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chantelle/eslint-plugin-chantelle/build/main' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/index.test' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chantelle/eslint-plugin-chantelle/build/main.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/build/main'>;
}
declare module '@chantelle/eslint-plugin-chantelle/index.test.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/index.test'>;
}
declare module '@chantelle/eslint-plugin-chantelle/src/index.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/src/index'>;
}
