// flow-typed signature: e8109e8dc58a7d79be5845950dc28c8d
// flow-typed version: <<STUB>>/@chantelle/eslint-config-chantelle_v^0.0.1-10/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chantelle/eslint-config-chantelle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chantelle/eslint-config-chantelle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@chantelle/eslint-config-chantelle/index' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle'>;
}
declare module '@chantelle/eslint-config-chantelle/index.js' {
  declare module.exports: $Exports<'@chantelle/eslint-config-chantelle'>;
}
