// flow-typed signature: c9ae5e5adc888b747a2c87135635e798
// flow-typed version: <<STUB>>/@chantelle/eslint-plugin-chantelle_v^0.0.1-y.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chantelle/eslint-plugin-chantelle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chantelle/eslint-plugin-chantelle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chantelle/eslint-plugin-chantelle/build/main' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/@chantelle/util_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/backpack-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/backpack-core-babel-7_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/eslint-config-cleanjs_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/flow-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/react-scripts_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/index.test' {
  declare module.exports: any;
}

declare module '@chantelle/eslint-plugin-chantelle/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chantelle/eslint-plugin-chantelle/build/main.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/build/main'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/@chantelle/util_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/@chantelle/util_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/backpack-core_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/backpack-core_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/backpack-core-babel-7_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/backpack-core-babel-7_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/eslint-config-cleanjs_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/eslint-config-cleanjs_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/flow-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/flow-runtime_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/jest_v22.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/lodash_v4.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/prettier_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/react-scripts_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/react-scripts_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/flow-typed/npm/webpack_vx.x.x'>;
}
declare module '@chantelle/eslint-plugin-chantelle/index.test.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/index.test'>;
}
declare module '@chantelle/eslint-plugin-chantelle/src/index.js' {
  declare module.exports: $Exports<'@chantelle/eslint-plugin-chantelle/src/index'>;
}
