module.exports = { //eslint-disable-line
  'react/no-deprecated': 2,
  'react/no-did-mount-set-state': 2,
  'react/no-did-update-set-state': 2,
  'react/no-direct-mutation-state': 2,
  'react/no-is-mounted': 2,
  'react/no-multi-comp': 0,
  'react/no-string-refs': 0,
  'react/no-unknown-property': 1,
  'react/require-extension': 0,
  'react/prefer-es6-class': 1,
  'react/prop-types': 1,
  'react/sort-comp': 0,
  'react/sort-prop-types': 0,
  'react/prefer-stateless-function': 1,
  'react/react-in-jsx-scope': 1,
  'react/self-closing-comp': 1,
  'react/wrap-multilines': [1, {
    'declaration': true,
    'assignment': true,
    'return': false,
  }],

  'babel/new-cap': 0,
  'babel/object-curly-spacing': [ 1, 'always' ],
  'babel/no-await-in-loop': 1,

  'react/jsx-boolean-value': [ 1, 'never' ],
  'react/jsx-closing-bracket-location': 2,
  'react/jsx-curly-spacing': [ 1, 'always' ],
  'react/jsx-equals-spacing': 1,
  'react/jsx-handler-names': 1,
  'react/jsx-indent-props': [ 1, 4 ],
  'react/jsx-indent': 1,
  'react/jsx-key': 2,
  'react/jsx-max-props-per-line': [ 1, { 'maximum': 1 } ],
  'react/jsx-no-bind': 0,
  'react/jsx-no-duplicate-props': 2,
  'react/jsx-no-literals': 0,
  'react/jsx-no-undef': 2,
  'react/jsx-pascal-case': 2,
  'react/jsx-sort-props': 0,
  'react/jsx-space-before-closing': 2,
  'react/jsx-uses-vars': 2,

  'flowtype/define-flow-type': 1,
  'flowtype/require-parameter-type': [ 2, { 'excludeArrowFunctions': true } ],
  'flowtype/require-return-type': [ 2, { 'excludeArrowFunctions': true } ],
  'flowtype/space-after-type-colon': 0,
  'flowtype/space-before-type-colon': 0,
  'flowtype/type-id-match': 0,
  'flowtype/use-flow-type': 1,
  'flowtype/valid-syntax': 2,

  'mocha/handle-done-callback': 2,
  'mocha/max-top-level-suites': 2,
  'mocha/no-exclusive-tests': 2,
  'mocha/no-global-tests': 2,
  'mocha/no-hooks': 0,
  'mocha/no-hooks-for-single-case': 0,
  'mocha/no-identical-title': 2,
  'mocha/no-mocha-arrows': 0,
  'mocha/no-pending-tests': 1,
  'mocha/no-return-and-callback': 2,
  'mocha/no-sibling-hooks': 2,
  'mocha/no-skipped-tests': 1,
  'mocha/no-synchronous-tests': 0,
  'mocha/no-top-level-hooks': 2,
  'mocha/valid-test-description': [ 1, '^((?!@now).)*$' ],
  'mocha/valid-suite-description': [ 1, '^((?!@now).)*$' ],
  'array-callback-return': 2,
  'arrow-parens': [ 2, 'as-needed' ],
  'comma-dangle': [ 2, 'always-multiline' ],
  'comma-style': [ 2, 'last', {
    'exceptions': { 'ArrayExpression': true, 'ObjectExpression': true },
  }],
  'computed-property-spacing': [ 1, 'always' ],
  'curly': 0,
  'eqeqeq': [ 2, 'smart' ],
  'generator-star-spacing': [ 2, 'both' ],
  'id-length': 0,
  'indent': [ 2, 4, { 'SwitchCase': 1 } ],
  'jsx-quotes': 2,
  'key-spacing': [ 2, {
    'beforeColon': false,
    'afterColon': true,
  }],
  'keyword-spacing': [ 2, { 'before': true, 'after': true, 'overrides': {
    'if': { 'after': false, 'before': true },
    'function': { 'after': false, 'before': true },
    'for': { 'after': false, 'before': true },
    'switch': { 'after': false, 'before': true },
    'catch': { 'after': false, 'before': true },
  } } ],
  'newline-before-return': 0,
  'no-alert': 0,
  'no-case-declarations': 1,
  'no-console': [ 2, { 'allow': [ 'warn', 'error', 'info' ] } ],
  'no-dupe-class-members': 2,
  'no-else-return': 0,
  'no-irregular-whitespace': 2,
  'no-nested-ternary': 0,
  'no-param-reassign': 0,
  'no-restricted-globals': 0,
  'no-shadow': 0, // redux requires unbound and bound in same file
  'no-multi-spaces': 0,
  'no-multiple-empty-lines': 0,
  'no-undef': 2,
  'no-unused-vars': [ 1, { 'varsIgnorePattern': 'React', 'args': 'none' } ],
  'no-use-before-define': 0,
  'no-useless-escape': 2,
  'new-cap': [ 2, { 'capIsNewExceptions': [ 'mongoose.Schema' ] } ],
  'object-curly-spacing': [ 1, 'always' ],
  'object-shorthand': 2,
  'padded-blocks': 0,
  'quotes': [ 2, 'single' ],
  'spaced-comments': 0,
  'space-before-function-paren': [ 2, 'never' ],
  'space-in-parens': [ 1, 'always', { 'exceptions': [ '{}', 'empty' ] } ],
  'space-unary-ops': [ 2, {
    'words': true,
    'nonwords': true,
    'overrides': { '++': false, '+': false, '--': false, '-': false } } ],
  'no-delete-var': 1,
  'no-self-assign': 2,
  'no-return-await': 2,
  'no-loop-func': 2,
  'no-unreachable': 2,
  'prefer-const': 0,
  'no-await-in-loop': 1,
  'semi': [ 1, 'never' ],
  'max-statements-per-line': [ 2, { 'max': 2 } ],
  'array-bracket-spacing': [ 0, 'always' ],
  'space-before-blocks': [ 2, 'always' ],
  'template-curly-spacing': [ 2, 'always' ],
  'max-len': [1, 80, 4],
  'max-nested-callbacks': ['error', 1],
}
